    location /servicios/alquileres {
        root   /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
        
        # Prevent caching of application files
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires -1;
    }
